version: "3"
services:
  # web:
  #   image: httpd
  #   container_name: apache
  #   ports:
  #     - "80:80"
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: httpd.access

  # fluentd:
  #   build: ./conf_fluentd
  #   container_name: fluentd
  #   volumes:
  #     - ./conf_fluentd/conf:/fluentd/etc
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=afrikpay-elastic"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.license.self_generated.type=trial"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=afrikpay-elastic
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "5601:5601"
